/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AnchorRouteImport } from './routes/anchor'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PostsRouteRouteImport } from './routes/posts.route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as ExpensiveIndexRouteImport } from './routes/expensive/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as FooBarRouteImport } from './routes/foo/bar'
import { Route as PathlessLayoutNestedLayoutRouteImport } from './routes/_pathlessLayout/nested-layout'
import { Route as AuthProfileRouteImport } from './routes/_auth.profile'
import { Route as DashboardUsersRouteRouteImport } from './routes/dashboard.users.route'
import { Route as DashboardInvoicesRouteRouteImport } from './routes/dashboard.invoices.route'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard.users.index'
import { Route as DashboardInvoicesIndexRouteImport } from './routes/dashboard.invoices.index'
import { Route as DashboardUsersUserRouteImport } from './routes/dashboard.users.user'
import { Route as DashboardInvoicesInvoiceIdRouteImport } from './routes/dashboard.invoices.$invoiceId'
import { Route as PathlessLayoutNestedLayoutRouteBRouteImport } from './routes/_pathlessLayout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteARouteImport } from './routes/_pathlessLayout/_nested-layout/route-a'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnchorRoute = AnchorRouteImport.update({
  id: '/anchor',
  path: '/anchor',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRouteRoute = PostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRouteRoute,
} as any)
const ExpensiveIndexRoute = ExpensiveIndexRouteImport.update({
  id: '/expensive/',
  path: '/expensive/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRouteRoute,
} as any)
const FooBarRoute = FooBarRouteImport.update({
  id: '/foo/bar',
  path: '/foo/bar',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRoute =
  PathlessLayoutNestedLayoutRouteImport.update({
    id: '/nested-layout',
    path: '/nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardUsersRouteRoute = DashboardUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInvoicesRouteRoute = DashboardInvoicesRouteRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardUsersRouteRoute,
} as any)
const DashboardInvoicesIndexRoute = DashboardInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardInvoicesRouteRoute,
} as any)
const DashboardUsersUserRoute = DashboardUsersUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => DashboardUsersRouteRoute,
} as any)
const DashboardInvoicesInvoiceIdRoute =
  DashboardInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => DashboardInvoicesRouteRoute,
  } as any)
const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBRouteImport.update({
    id: '/_nested-layout/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteARouteImport.update({
    id: '/_nested-layout/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/posts': typeof PostsRouteRouteWithChildren
  '/anchor': typeof AnchorRoute
  '/login': typeof LoginRoute
  '/dashboard/invoices': typeof DashboardInvoicesRouteRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRouteRouteWithChildren
  '/profile': typeof AuthProfileRoute
  '/nested-layout': typeof PathlessLayoutNestedLayoutRoute
  '/foo/bar': typeof FooBarRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/expensive': typeof ExpensiveIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/dashboard/invoices/$invoiceId': typeof DashboardInvoicesInvoiceIdRoute
  '/dashboard/users/user': typeof DashboardUsersUserRoute
  '/dashboard/invoices/': typeof DashboardInvoicesIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anchor': typeof AnchorRoute
  '/login': typeof LoginRoute
  '/profile': typeof AuthProfileRoute
  '/nested-layout': typeof PathlessLayoutNestedLayoutRoute
  '/foo/bar': typeof FooBarRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/expensive': typeof ExpensiveIndexRoute
  '/posts': typeof PostsIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/dashboard/invoices/$invoiceId': typeof DashboardInvoicesInvoiceIdRoute
  '/dashboard/users/user': typeof DashboardUsersUserRoute
  '/dashboard/invoices': typeof DashboardInvoicesIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/posts': typeof PostsRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/anchor': typeof AnchorRoute
  '/login': typeof LoginRoute
  '/dashboard/invoices': typeof DashboardInvoicesRouteRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRouteRouteWithChildren
  '/_auth/profile': typeof AuthProfileRoute
  '/_pathlessLayout/nested-layout': typeof PathlessLayoutNestedLayoutRoute
  '/foo/bar': typeof FooBarRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/expensive/': typeof ExpensiveIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/_pathlessLayout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathlessLayout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/dashboard/invoices/$invoiceId': typeof DashboardInvoicesInvoiceIdRoute
  '/dashboard/users/user': typeof DashboardUsersUserRoute
  '/dashboard/invoices/': typeof DashboardInvoicesIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/posts'
    | '/anchor'
    | '/login'
    | '/dashboard/invoices'
    | '/dashboard/users'
    | '/profile'
    | '/nested-layout'
    | '/foo/bar'
    | '/posts/$postId'
    | '/dashboard/'
    | '/expensive'
    | '/posts/'
    | '/route-a'
    | '/route-b'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/users/user'
    | '/dashboard/invoices/'
    | '/dashboard/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anchor'
    | '/login'
    | '/profile'
    | '/nested-layout'
    | '/foo/bar'
    | '/posts/$postId'
    | '/dashboard'
    | '/expensive'
    | '/posts'
    | '/route-a'
    | '/route-b'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/users/user'
    | '/dashboard/invoices'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/posts'
    | '/_auth'
    | '/_pathlessLayout'
    | '/anchor'
    | '/login'
    | '/dashboard/invoices'
    | '/dashboard/users'
    | '/_auth/profile'
    | '/_pathlessLayout/nested-layout'
    | '/foo/bar'
    | '/posts/$postId'
    | '/dashboard/'
    | '/expensive/'
    | '/posts/'
    | '/_pathlessLayout/_nested-layout/route-a'
    | '/_pathlessLayout/_nested-layout/route-b'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/users/user'
    | '/dashboard/invoices/'
    | '/dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  PostsRouteRoute: typeof PostsRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  AnchorRoute: typeof AnchorRoute
  LoginRoute: typeof LoginRoute
  FooBarRoute: typeof FooBarRoute
  ExpensiveIndexRoute: typeof ExpensiveIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anchor': {
      id: '/anchor'
      path: '/anchor'
      fullPath: '/anchor'
      preLoaderRoute: typeof AnchorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/expensive/': {
      id: '/expensive/'
      path: '/expensive'
      fullPath: '/expensive'
      preLoaderRoute: typeof ExpensiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/foo/bar': {
      id: '/foo/bar'
      path: '/foo/bar'
      fullPath: '/foo/bar'
      preLoaderRoute: typeof FooBarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/nested-layout': {
      id: '/_pathlessLayout/nested-layout'
      path: '/nested-layout'
      fullPath: '/nested-layout'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardUsersRouteRoute
    }
    '/dashboard/invoices/': {
      id: '/dashboard/invoices/'
      path: '/'
      fullPath: '/dashboard/invoices/'
      preLoaderRoute: typeof DashboardInvoicesIndexRouteImport
      parentRoute: typeof DashboardInvoicesRouteRoute
    }
    '/dashboard/users/user': {
      id: '/dashboard/users/user'
      path: '/user'
      fullPath: '/dashboard/users/user'
      preLoaderRoute: typeof DashboardUsersUserRouteImport
      parentRoute: typeof DashboardUsersRouteRoute
    }
    '/dashboard/invoices/$invoiceId': {
      id: '/dashboard/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/dashboard/invoices/$invoiceId'
      preLoaderRoute: typeof DashboardInvoicesInvoiceIdRouteImport
      parentRoute: typeof DashboardInvoicesRouteRoute
    }
    '/_pathlessLayout/_nested-layout/route-b': {
      id: '/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/_nested-layout/route-a': {
      id: '/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteARouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
  }
}

interface DashboardInvoicesRouteRouteChildren {
  DashboardInvoicesInvoiceIdRoute: typeof DashboardInvoicesInvoiceIdRoute
  DashboardInvoicesIndexRoute: typeof DashboardInvoicesIndexRoute
}

const DashboardInvoicesRouteRouteChildren: DashboardInvoicesRouteRouteChildren =
  {
    DashboardInvoicesInvoiceIdRoute: DashboardInvoicesInvoiceIdRoute,
    DashboardInvoicesIndexRoute: DashboardInvoicesIndexRoute,
  }

const DashboardInvoicesRouteRouteWithChildren =
  DashboardInvoicesRouteRoute._addFileChildren(
    DashboardInvoicesRouteRouteChildren,
  )

interface DashboardUsersRouteRouteChildren {
  DashboardUsersUserRoute: typeof DashboardUsersUserRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardUsersRouteRouteChildren: DashboardUsersRouteRouteChildren = {
  DashboardUsersUserRoute: DashboardUsersUserRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardUsersRouteRouteWithChildren =
  DashboardUsersRouteRoute._addFileChildren(DashboardUsersRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardInvoicesRouteRoute: typeof DashboardInvoicesRouteRouteWithChildren
  DashboardUsersRouteRoute: typeof DashboardUsersRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardInvoicesRouteRoute: DashboardInvoicesRouteRouteWithChildren,
  DashboardUsersRouteRoute: DashboardUsersRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface PostsRouteRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteRouteChildren: PostsRouteRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteRouteWithChildren = PostsRouteRoute._addFileChildren(
  PostsRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthProfileRoute: typeof AuthProfileRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthProfileRoute: AuthProfileRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRoute
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRoute,
  PathlessLayoutNestedLayoutRouteARoute: PathlessLayoutNestedLayoutRouteARoute,
  PathlessLayoutNestedLayoutRouteBRoute: PathlessLayoutNestedLayoutRouteBRoute,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  PostsRouteRoute: PostsRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  AnchorRoute: AnchorRoute,
  LoginRoute: LoginRoute,
  FooBarRoute: FooBarRoute,
  ExpensiveIndexRoute: ExpensiveIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
